### PR TITLE
Simplify with macros

### PR DESCRIPTION
**Pull request by dragoncoder047**
https://github.com/technoblogy/ulisp/issues/53

this should hopefully make the big lists of strings (names and docstrings) using macros.

i don't know enough about how ulisp builder works to be able to get the table entries with a macro. maybe later.

### CODE REVIEW

**Comment by technoblogy** [comment]
My problem with using macros is that someone looking at the code and trying to understand it has to look up the definition of the macro. In other words, it adds a level of indirection.

I agree that it makes the source shorter, but I'm not sure it makes the source clearer.

**Comment by dragoncoder047** [comment]
I was afraid of that. With an appropriately named macro it should still be clear, though -- Arduino `abs`, `sq`, `min`, `max`, etc. are all actually implemented as macros and they work well enough. (My beef is that `map` is *not* implemented as a macro so you end up losing floating point precision. I digress.)

Anyway, the macro also helps a hacker of uLisp (like me!!!) write less and also make sure that it's formatted properly (the preprocessor and/or compiler will complain if you mess up) and you can also call things "foo" and "foo" in two different macros and they will be renamed to "string_foo" and "doc_foo" to prevent name clashes, automatically.

**Comment by technoblogy** [comment]
OK, I see your point. I'll think about it a bit more.

Ideally it would be good to integrate the function name enum, the symbol names, the documentation strings, and the lookup_table[] entry into a single macro call, but I can't see how to do that without using my uLisp Builder.

**Comment by dragoncoder047** [comment]
> Ideally it would be good to integrate the function name enum, the symbol names, the documentation strings, and the lookup_table[] entry into a single macro call, but I can't see how to do that without using my uLisp Builder.

I was hoping for that too. I unfortunately don't know how or I would have [mentioned it earlier](https://github.com/technoblogy/ulisp/issues/52#issuecomment-1187601166).

However, I did just learn that `.hpp` files can be used to include code, but not have it be compiled individually and run into linker errors. Maybe that would work (and possibly even dispense with the need for uLisp Builder).

**Comment by dragoncoder047** [comment]
Another idea that I have no idea how to implement, but would improve readability/hackability: Group the function definitions next to their corresponding `stringNNN` and `docNNN` data so it reads string_foo, doc_foo, fn_foo, string_bar, doc_bar, fn_bar, etc. instead of huge blocks of strings forcing the user to scroll up and down on everything.

Because the enum and lookup table are enclosed in {} I don't know how (or even whether it is possible) to do the same with those. Perhaps another format is needed.

**Comment by technoblogy** [comment]
It would be easy to do in the Lisp Builder, but because it's only a partial solution I'm inclined to leave things as they are for the moment until I can think of a better complete solution. But thanks for the suggestions!

**Comment by dragoncoder047** [comment]
I'm not sure, but couldn't the strings be written inline in the lookup table using the `PSTR()` macro? then there could be a single table macro like so:

```cpp
#define MYMACRO(nn, fn, meta, doc) { PSTR(#nn), fn, meta, PSTR(doc) },
MYMACRO(foo-bar, fn_foo_bar, 0x100, "Foo the bar"); // <-- note symbol name is NOT in quotes
// expands to { PSTR("foo-bar"), fn_foo_bar, 0x100, PSTR("Foo the bar") }
```

?

Maybe also put some functions inline with `[=](params)->return_type{code}` lambda expression too? I know nothing about lambdas!!

**Comment by technoblogy** [comment]
I don't think you can put the strings inline in the lookup table. I think I tried it in the early days, and it didn't work, but I can't quite remember why.

**Comment by dragoncoder047** [comment]
> OK, I see your point. I'll think about it a bit more.
> 
> Ideally it would be good to integrate the function name enum, the symbol names, the documentation strings, and the lookup_table[] entry into a single macro call, but I can't see how to do that without using my uLisp Builder.

Sorry for the necropost, but I just noticed that this could be acheivable uing someting called the "X macro hack" and passing macros as arguments to other macros: https://hackaday.com/2023/03/16/the-x-macro-a-historic-preprocessor-hack/

**Comment by technoblogy** [comment]
I'm about to release a new version 4.4 of uLisp that reorganises the way the lookup table works that should make this easier. Hopefully it should appear later this week.

**Comment by dragoncoder047** [comment]
uLisp 4.4 looks like it would be easy to add user extensions without resorting to macro hacks, so I'll close this.

**Pull request closed without merging**
